apiVersion: v1
kind: Service
metadata:
  name: my-helloWorld-svc
  labels:
    app: HelloWorld
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: HelloWorld
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-helloWorld-app
  labels:
    app: HelloWorld
spec:
  replicas: 3
  selector:
    matchLabels:
      app: HelloWorld
  template:
    metadata:
      labels:
        app: HelloWorld
    spec:
      containers:
      - name: HelloWorld
        image: codehero92/hello-world-webapp
        ports:
        - containerPort: 8080
