apiVersion: v1
kind: Service
metadata:
  name: my-helloworld-service
  labels:
    app: helloworld
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: helloworld
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-helloworld-app
  labels:
    app: helloworld
spec:
  replicas: 3
  selector:
    matchLabels:
      app: helloworld
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      containers:
      - name: helloworld
        image: codehero92/hello-world-webapp:hello-world-webapp
        ports:
        - containerPort: 8080
